// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_collect_300_stars = "CgkIxNfOiYMdEAIQDQ"; // <GPGSID>
        public const string achievement_collect_1500_stars = "CgkIxNfOiYMdEAIQEg"; // <GPGSID>
        public const string achievement_clear_700_level = "CgkIxNfOiYMdEAIQBQ"; // <GPGSID>
        public const string achievement_clear_500_level = "CgkIxNfOiYMdEAIQBA"; // <GPGSID>
        public const string achievement_clear_300_level = "CgkIxNfOiYMdEAIQAw"; // <GPGSID>
        public const string achievement_collect_500_stars = "CgkIxNfOiYMdEAIQDg"; // <GPGSID>
        public const string achievement_clear_10_level = "CgkIxNfOiYMdEAIQAA"; // <GPGSID>
        public const string achievement_clear_100_level = "CgkIxNfOiYMdEAIQAg"; // <GPGSID>
        public const string achievement_collect_2000_stars = "CgkIxNfOiYMdEAIQEw"; // <GPGSID>
        public const string achievement_collect_900_stars = "CgkIxNfOiYMdEAIQEA"; // <GPGSID>
        public const string achievement_collect_700_stars = "CgkIxNfOiYMdEAIQDw"; // <GPGSID>
        public const string achievement_clear_2500_level = "CgkIxNfOiYMdEAIQCQ"; // <GPGSID>
        public const string achievement_collect_200_stars = "CgkIxNfOiYMdEAIQDA"; // <GPGSID>
        public const string achievement_clear_1500_level = "CgkIxNfOiYMdEAIQBw"; // <GPGSID>
        public const string achievement_clear_50_level = "CgkIxNfOiYMdEAIQAQ"; // <GPGSID>
        public const string achievement_clear_2000_level = "CgkIxNfOiYMdEAIQCA"; // <GPGSID>
        public const string achievement_collect_1000_stars = "CgkIxNfOiYMdEAIQEQ"; // <GPGSID>
        public const string achievement_clear_1000_level = "CgkIxNfOiYMdEAIQBg"; // <GPGSID>
        public const string achievement_collect_3000_stars = "CgkIxNfOiYMdEAIQFA"; // <GPGSID>
        public const string achievement_clear_3000_level = "CgkIxNfOiYMdEAIQCg"; // <GPGSID>
        public const string achievement_collect_100_stars = "CgkIxNfOiYMdEAIQCw"; // <GPGSID>

}

